# -*- coding: utf-8 -*-
"""EDA: Credit Card Fraud Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KiCr7LgATpRPJ6AmBw3t9bZ0PvvAC1NG
"""

# Import libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset

df = pd.read_csv('creditcard.csv')

# Basic information about the dataset

print("Dataset shape:", df.shape)
print("Columns:", df.columns)

# Data summary

print("Data Summary:")
print(df.describe())

# Check for missing values

print("Missing Values:")
print(df.isnull().sum())

# Class distribution

print("Class Distribution:")
print(df['Class'].value_counts())

"""## Data visualization"""

# Histogram of numeric features

numeric_features = df.select_dtypes(include=np.number).columns
df[numeric_features].hist(bins=20, figsize=(12, 10))
plt.tight_layout()
plt.show()

# Box plot of numeric features by Class

plt.figure(figsize=(10, 8))
sns.boxplot(x=df['Class'], y=df['V24'])
plt.title("Boxplot of V24 by Class")
plt.xlabel("Class")
plt.ylabel("V24")
plt.show()

# Countplot

plt.figure(figsize=(10, 6))
sns.countplot(x='Class', data=df)
plt.title('Countplot')
plt.show()

# Heatmap

plt.figure(figsize=(12, 10))
corr_matrix = df.corr()
cmap = sns.diverging_palette(230, 20, as_cmap=True)
sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap=cmap, center=0, annot_kws={"size": 8})
plt.xticks(rotation=45, ha="right", fontsize=8)
plt.yticks(fontsize=8)
plt.title("Correlation Heatmap")
plt.tight_layout()
plt.show()

"""## Advanced Analysis"""

# Scatter plot

plt.figure(figsize=(10, 6))
sns.scatterplot(x='V1', y='V2', hue='Class', data=df)
plt.title('Scatter Plot between V1 and V2')
plt.show()

# Time series analysis - Line Plot

plt.figure(figsize=(10, 6))
plt.plot(df['Time'], df['Amount'])
plt.xlabel('Time')
plt.ylabel('Amount')
plt.title('Time Series Analysis of Transaction Amount')
plt.show()

# Outlier detection using IQR

Q1 = df['Amount'].quantile(0.25)
Q3 = df['Amount'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df['Amount'] < lower_bound) | (df['Amount'] > upper_bound)]
print("Outliers:")
print(outliers)

# Save the updated dataset

df.to_csv('creditcard_processed.csv', index=False)