# -*- coding: utf-8 -*-
"""Twitter Reviews.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11xEzv-I6NYwnUsiuoKASR5oQERBqbPlw
"""

# Import libraries

import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag
from textblob import TextBlob

# Load the dataset

df = pd.read_csv('Twitter_Reviews.csv')

# Print first 5 rows of dataset

df.head()

# Tokenization

df['Tokens'] = df['Comment'].apply(lambda x: word_tokenize(x))

# POS tagging

df['POS_tags'] = df['Tokens'].apply(lambda x: pos_tag(x))

# Sentiment analysis

df['Sentiment'] = df['Comment'].apply(lambda x: TextBlob(x).sentiment.polarity)

# Function to classify sentiment based on polarity score

def classify_sentiment(score):
    if score > 0:
        return 'Positive'
    elif score < 0:
        return 'Negative'
    else:
        return 'Neutral'

# Classify sentiment using polarity score

df['Sentiment_Classification'] = df['Sentiment'].apply(classify_sentiment)

# Print the updated dataframe

df[['Comment', 'Tokens', 'POS_tags', 'Sentiment', 'Sentiment_Classification']]